server:
  port: 8080
  error:
    include-message: always
  forward-headers-strategy: framework

application:
  stock-url: ${STOCK_SVC_URL:http://localhost:8081/}
  product-url: ${PRODUCT_SVC_URL:http://localhost:8080/}

spring:
  sql:
    init:
      mode: always
  datasource:
    hikari:
      maximum-pool-size: 5
      connection-timeout: 20000
    url: jdbc:postgresql://${CART_DB_URL:localhost:9082}/cart
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
