{{- if .Values.postgres.enabled  -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-db
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-db
    spec:
      containers:
        - name: postgres
          image: postgres:14.1
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.db.name }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.postgres.db.password }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-db
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: {{ .Release.Name }}-db
{{- end -}}
