---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
  namespace: microservices
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
  strategy: {}
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
        - image: apache/kafka-native:latest
          imagePullPolicy: Always
          name: kafka-cluster
          env:
            - name: KAFKA_NODE_ID
              value: "1"
            - name: KAFKA_PROCESS_ROLES
              value: broker,controller
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@localhost:9091
            - name: KAFKA_LISTENERS
              value: CONTROLLER://localhost:9091,K8S://0.0.0.0:9092,HOST://0.0.0.0:9093
            - name: KAFKA_ADVERTISED_LISTENERS
              value: K8S://kafka-cluster:9092,HOST://localhost:9093
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,K8S:PLAINTEXT,HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: K8S
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: "1"
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kafka-cluster
  name: kafka-cluster
  namespace: microservices
spec:
  ports:
    - name: http
      port: 9092
      protocol: TCP
      targetPort: 9092
  selector:
    app: kafka-cluster
  type: ClusterIP
