name: Build Shopping Cart Service

on:
  push:
    paths:
      - "microservices/shopping-cart/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: ./.github/workflows/build-microservice.yml
    with:
      service-name: shopping-cart
