name: Build Stock Service

on:
  push:
    paths:
      - "microservices/stock/**"
      - "!microservices/stock/infra/**"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  call-build:
    uses: ./.github/workflows/build-microservice.yml
    with:
      service-name: stock
