name: Deploy presentation slides

on:
  workflow_dispatch:
  push:
    paths:
      - ".github/workflows/deploy-presentation.yml"
      - "presentation-slides/**"
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./presentation-slides

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: |
          npm install -g yarn
          yarn install

      - name: Build
        # Doc for base url: https://sli.dev/guide/hosting#base
        run: yarn build --base /${{github.event.repository.name}}/

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: List build output
        run: ls -l

      - name: Upload build artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: presentation-slides/dist # explicit base path, check https://github.com/actions/upload-pages-artifact/issues/52

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./presentation-slides
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
